Repository woowa-techcamp-2021/cashbook-12, pull requests merged in 2021-07, with the labels that each got.

#7 프론트엔드 개발 환경 설정
  .gitignore
  .prettierrc
  client/.eslintrc
  client/config/paths.js
  client/config/webpack.common.js
  client/config/webpack.dev.js
  client/config/webpack.prod.js
  client/package.json
  client/public/favicon.png
  client/public/index.html
  client/src/index.js
  client/yarn.lock
  server/.eslintrc
  server/package.json
  server/yarn.lock
Labels: setting

#8 프론트엔드 컴포넌트 구조 생성
  .gitignore
  client/.env.example
  client/.eslintrc
  client/config/env.js
  client/config/webpack.common.js
  client/config/webpack.dev.js
  client/package.json
  client/src/assets/icons/calendar.svg
  client/src/assets/icons/chart.svg
  client/src/assets/icons/check.svg
  client/src/assets/icons/file-text.svg
  client/src/index.js
  client/src/lib/Component.js
  client/src/lib/Observable.js
  client/src/store/Count.js
  client/src/store/Name.js
  client/src/store/index.js
  client/src/styles/_colors.scss
  client/src/styles/_font-styles.scss
  client/src/styles/base.scss
  client/src/utils/api.js
  client/src/views/pages/MainPage/MainPage.js
  client/src/views/pages/MainPage/MainPage.scss
  client/src/views/pages/NotFoundPage/NotFoundPage.js
  client/src/views/pages/NotFoundPage/NotFoundPage.scss
  client/src/views/pages/index.js
  client/yarn.lock
Labels: setting

#10 백엔드 프로젝트 생성
  .gitignore
  client/config/paths.js
  client/package.json
  client/public/favicon.png
  server/.env.example
  server/.eslintignore
  server/.eslintrc
  server/package.json
  server/src/api/index.js
  server/src/api/routes/user/index.js
  server/src/api/routes/user/user.controller.js
  server/src/app.js
  server/src/config/database.js
  server/src/config/index.js
  server/src/loaders/express.js
  server/src/loaders/index.js
  server/src/loaders/logger.js
  server/src/loaders/sequelize.js
  server/src/models/category.js
  server/src/models/history.js
  server/src/models/index.js
  server/src/models/payment.js
  server/src/models/user.js
  server/src/services/user.js
  server/yarn.lock
Labels: back-end

#12 클라이언트 라우터, 렌더링
  client/.eslintrc
  client/config/paths.js
  client/config/webpack.common.js
  client/config/webpack.dev.js
  client/src/index.js
  client/src/lib/Component.js
  client/src/lib/Router.js
  client/src/store/Count.js
  client/src/store/Name.js
  client/src/utils/api.js
  client/src/utils/helper.js
  client/src/views/components/common/Layout/Layout.js
  client/src/views/components/form/Input/Input.js
  client/src/views/components/index.js
  client/src/views/pages/LoginPage/LoginPage.js
  client/src/views/pages/LoginPage/LoginPage.scss
  client/src/views/pages/MainPage/MainPage.js
  client/src/views/pages/NotFoundPage/NotFoundPage.js
  client/src/views/pages/index.js
Labels: setting

#19 컴포넌트 렌더링 방식 변경 및 차트 페이지 마크업
  .github/workflows/lint-check.yml
  README.md
  client/.eslintrc
  client/config/webpack.common.js
  client/package.json
  client/public/favicon.png
  client/src/assets/icons/calendar.js
  client/src/assets/icons/calendar.svg
  client/src/assets/icons/chart.js
  client/src/assets/icons/chart.svg
  client/src/assets/icons/check.js
  client/src/assets/icons/check.svg
  client/src/assets/icons/file-text.js
  client/src/assets/icons/file-text.svg
  client/src/assets/icons/index.js
  client/src/lib/Component.js
  client/src/lib/Router.js
  client/src/styles/_font-styles.scss
  client/src/styles/base.scss
  client/src/views/components/chart/Donut/Donut.js
  client/src/views/components/chart/Donut/Donut.scss
  client/src/views/components/chart/Linear/Linear.js
  client/src/views/components/chart/Linear/Linear.scss
  client/src/views/components/chart/Wrapper/Wrapper.js
  client/src/views/components/chart/Wrapper/Wrapper.scss
  client/src/views/components/common/Header/Header.js
  client/src/views/components/common/Header/Header.scss
  client/src/views/components/common/Layout/Layout.js
  client/src/views/components/common/Layout/Layout.scss
  client/src/views/components/form/Input/Input.js
  client/src/views/components/index.js
  client/src/views/pages/LoginPage/LoginPage.js
  client/src/views/pages/MainPage/MainPage.js
  client/src/views/pages/MainPage/MainPage.scss
  client/src/views/pages/NotFoundPage/NotFoundPage.js
  client/yarn.lock
Labels: front-end

#20 v1.0.0
  .github/workflows/lint-check.yml
  README.md
  client/.eslintrc
  client/config/webpack.common.js
  client/package.json
  client/public/favicon.png
  client/src/assets/icons/calendar.js
  client/src/assets/icons/calendar.svg
  client/src/assets/icons/chart.js
  client/src/assets/icons/chart.svg
  client/src/assets/icons/check.js
  client/src/assets/icons/check.svg
  client/src/assets/icons/file-text.js
  client/src/assets/icons/file-text.svg
  client/src/assets/icons/index.js
  client/src/lib/Component.js
  client/src/lib/Router.js
  client/src/styles/_font-styles.scss
  client/src/styles/base.scss
  client/src/views/components/chart/Donut/Donut.js
  client/src/views/components/chart/Donut/Donut.scss
  client/src/views/components/chart/Linear/Linear.js
  client/src/views/components/chart/Linear/Linear.scss
  client/src/views/components/chart/Wrapper/Wrapper.js
  client/src/views/components/chart/Wrapper/Wrapper.scss
  client/src/views/components/common/Header/Header.js
  client/src/views/components/common/Header/Header.scss
  client/src/views/components/common/Layout/Layout.js
  client/src/views/components/common/Layout/Layout.scss
  client/src/views/components/form/Input/Input.js
  client/src/views/components/index.js
  client/src/views/pages/LoginPage/LoginPage.js
  client/src/views/pages/MainPage/MainPage.js
  client/src/views/pages/MainPage/MainPage.scss
  client/src/views/pages/NotFoundPage/NotFoundPage.js
  client/yarn.lock
Labels: v1.0.0
